name: Build & Test Template

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string

jobs:
  build_and_test:
    name: Build Project & Run Tests
    runs-on: 'ubuntu-22.04'
    defaults:
      run:
        working-directory: src/${{ inputs.working_directory }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup .NET ${{ inputs.dotnet_version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Package Cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install & Configure Spatialite
        if: ${{ inputs.working_directory == 'service/service-directory-api' }}
        shell: bash
        run: |
          sudo apt-get install libspatialite-dev libsqlite3-mod-spatialite -y
          sudo ldconfig "/usr/lib/x86_64-linux-gnu/mod_spatialite.so"
          
      - name: Restore Project
        shell: bash
        run: dotnet restore

      - name: Build Project
        shell: bash
        run: dotnet build --no-restore

      - name: Test Project
        shell: bash
        run: dotnet test --no-build --no-restore --verbosity minimal