name: Stryker Template

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      project_directory:
        required: true
        type: string
      artifact:
        required: true
        type: string
      runs_on:
        required: true
        type: string

jobs:
  build_and_test:
    name: Build Project & Run Stryker
    runs-on: ${{ inputs.runs_on }}
    defaults:
      run:
        working-directory: src/${{ inputs.working_directory }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup .NET ${{ inputs.dotnet_version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Setup Stryker.NET
        shell: bash
        run: dotnet tool install -g dotnet-stryker

      - name: Package Cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Run Stryker
        shell: bash
        working-directory: src/${{ inputs.working_directory }}/${{ inputs.project_directory }}
        run: dotnet stryker --reporter "markdown" --reporter "html"

      - name: Title markdown
        run: echo '### Stryker Results ðŸš€' >> $GITHUB_STEP_SUMMARY

      - name: Adding markdown
        run: cat ${{ inputs.project_directory }}/StrykerOutput/**/**/*.md >> $GITHUB_STEP_SUMMARY

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stryker-${{ inputs.artifact }}
          path: src/${{ inputs.working_directory }}/${{ inputs.project_directory }}/StrykerOutput/**/**/*.html
          if-no-files-found: error
